name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install hdf5-mpi
        run: brew install hdf5-mpi
      - name: Compile test file
        run: h5pfc test.f90
